SELECT * FROM `ARTICLE`;
SELECT REF,DESIGNATION FROM `ARTICLE` WHERE PRIX>2; 
SELECT REF,DESIGNATION FROM `ARTICLE` WHERE PRIX BETWEEN 2 AND 6.25; 
SELECT REF,DESIGNATION FROM `ARTICLE` WHERE PRIX> 2 AND PRIX< 6.25; 
SELECT REF,DESIGNATION FROM `ARTICLE` WHERE PRIX NOT BETWEEN 2 AND 6.25; 
SELECT * FROM `ARTICLE`,`FOURNISSEUR` WHERE ARTICLE.ID_FOU = FOURNISSEUR.ID AND (FOURNISSEUR.NOM = "Française d'imports" OR FOURNISSEUR.NOM = "Dubois & Fils");

SELECT * FROM `ARTICLE`,`FOURNISSEUR` WHERE ARTICLE.ID_FOU = FOURNISSEUR.ID AND FOURNISSEUR.NOM in ('Française d\'imports','Dubois & Fils'); 

SELECT * FROM `ARTICLE`,`FOURNISSEUR` WHERE ARTICLE.ID_FOU = FOURNISSEUR.ID AND FOURNISSEUR.NOM NOT IN ('Française d\'imports','Dubois & Fils'); 

SELECT * FROM `BON` WHERE `DATE_CMDE` BETWEEN '2019-02-01' AND '2019-04-30';
