SELECT * FROM `ARTICLE` ORDER BY `ARTICLE`.`DESIGNATION` ASC;
SELECT * FROM `ARTICLE` ORDER BY `ARTICLE`.`PRIX` DESC;
SELECT * FROM `ARTICLE` WHERE `DESIGNATION` LIKE '%boulon%' ORDER BY `PRIX` DESC;
SELECT * FROM `ARTICLE` WHERE `DESIGNATION` LIKE '%sachet%';

SELECT ARTICLE.*, FOURNISSEUR.* FROM `ARTICLE`, `FOURNISSEUR` WHERE ARTICLE.ID_FOU = FOURNISSEUR.ID ORDER BY FOURNISSEUR.NOM ASC, ARTICLE.PRIX DESC; 

SELECT ARTICLE.*, FOURNISSEUR.* FROM `ARTICLE`, `FOURNISSEUR` WHERE ARTICLE.ID_FOU = FOURNISSEUR.ID AND FOURNISSEUR.NOM = 'Dubois & Fils';

SELECT FOURNISSEUR.NOM, AVG(ARTICLE.PRIX) AS PrixMoyen FROM `ARTICLE`, `FOURNISSEUR` WHERE ARTICLE.ID_FOU = FOURNISSEUR.ID AND FOURNISSEUR.NOM = 'Dubois & Fils' GROUP BY FOURNISSEUR.NOM; 

SELECT FOURNISSEUR.NOM, AVG(ARTICLE.PRIX) AS PrixMoyen FROM `ARTICLE` JOIN `FOURNISSEUR` ON ARTICLE.ID_FOU = FOURNISSEUR.ID GROUP BY FOURNISSEUR.NOM; 

SELECT * FROM `BON` WHERE DATE_CMDE BETWEEN '2019/03/01' and '2019/04/05';

k.
SELECT BON.NUMERO, ARTICLE.DESIGNATION FROM BON 
JOIN COMPO ON BON.ID = COMPO.ID_BON 
JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID 
WHERE ARTICLE.DESIGNATION LIKE '%boulon%'; 

l.
SELECT BON.NUMERO, ARTICLE.DESIGNATION, FOURNISSEUR.NOM FROM BON 
JOIN COMPO ON BON.ID = COMPO.ID_BON 
JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID 
JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
WHERE ARTICLE.DESIGNATION LIKE '%boulon%'; 

m.
SELECT BON.NUMERO, SUM(ARTICLE.PRIX) AS PrixTotal FROM BON JOIN COMPO ON BON.ID = COMPO.ID_BON JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID GROUP BY BON.NUMERO; 

n.
SELECT BON.NUMERO, SUM(COMPO.QTE) AS PrixTotal FROM BON JOIN COMPO ON BON.ID = COMPO.ID_BON JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID GROUP BY BON.NUMERO; 

o.
SELECT BON.NUMERO, SUM(COMPO.QTE) AS QuantiteTotale FROM BON JOIN COMPO ON BON.ID = COMPO.ID_BON JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID GROUP BY BON.NUMERO HAVING SUM(COMPO.QTE) > 25; 

p.
SELECT COALESCE(SUM(COMPO.QTE * ARTICLE.PRIX), 0) AS CoutTotal
FROM BON
JOIN COMPO ON BON.ID = COMPO.ID_BON
JOIN ARTICLE ON COMPO.ID_ART = ARTICLE.ID
WHERE MONTH(BON.DATE_CMDE) = 4 AND YEAR(BON.DATE_CMDE) = 2019;

