UPDATE ARTICLE
SET DESIGNATION = UPPER(DESIGNATION)
WHERE PRIX > 10;

UPDATE ARTICLE
SET DESIGNATION = LOWER(DESIGNATION)
WHERE id = 2;

UPDATE ARTICLE
JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID
SET ARTICLE.PRIX = ARTICLE.PRIX * 1.10
WHERE FOURNISSEUR.NOM = 'FDM SA';

